[package]
name = "Discord-Encrypted-Storage-Explorer"
authors = ["Obfusque"]
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10"
base64 = "0.22.1"
regex = "1"
serde_json = "1"
anyhow = "1"
windows = { version = "0.62.0", features = ["Win32_Security_Cryptography"] }

